### ISSUE TITLE
Alpha color for highlight is kind of low constrast

### ISSUE THREAD

**Issue by ng-hai** [rose-pine/palette#7]
I received an issue about low contrast of `highlight` colors in Blink SH terminal, even when using `highlightHigh` value.

Should the palette be updated for the new one? 🤔 

ng-hai/rose-pine-blinksh#4

**Comment by mvllow** [comment]
<img width="452" alt="Highlight high in Neovim" src="https://user-images.githubusercontent.com/1474821/206863698-d355b563-e6b7-49b7-818b-c9232b59ec3c.png">

_Highlight in Neovim_

Neovim could be a good reference for our newer (unofficial-ish) highlight colours. I believe it is along the lines of muted with alpha 10%, 20% and 30%. We have been playing around with new highlight colours for a while now to improve contrast and consistency but haven't had time to really push this forward.

Let me know if that makes sense/improves contrast for you. Would love any feedback as we are debating using the alpha of our muted colour or maybe new colours altogether.

**Comment by rpopic2** [comment]
Glad to hear that as a nvim user! Definitely looking forward to it

**Comment by ng-hai** [comment]
Really need @rpopic2 help on Blink SH side because I've not been using it for a while.

**Comment by ng-hai** [comment]
For visualization
<img width="415" alt="image" src="https://user-images.githubusercontent.com/19520278/211516361-1ccd6a78-4724-45e7-bd20-50a8db7a4b3f.png">

**Comment by mvllow** [comment]
We are revisiting the Moon and Dawn palettes with a heavier focus on accessibility. Any feedback would be appreciated in our Discord discussion :)

https://discord.com/channels/1090681740865052722/1107674766577516686/1107674766577516686
